name: CI
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test-python:
    runs-on: ubuntu-latest
    env:
      AWS_PROFILE: any-profile
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest
      - name: Run Ruff
        uses: chartboost/ruff-action@v1

  build-docs:
    needs: test-python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --group docs
      - name: Build documentation
        run: uv run mkdocs build --strict
      - name: Check build result
        run: |
          if [ ! -d "site" ]; then
            echo "Documentation build failed"
            exit 1
          fi
      - name: Upload built docs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write # Required for GitHub Pages deployment

    steps:
      - name: Download built docs artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
